/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const PlanMetadata = IDL.Record({
  'title' : IDL.Text,
  'creator' : IDL.Principal,
  'createdAt' : Time,
  'description' : IDL.Text,
  'updatedAt' : Time,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const StructuredPlan = IDL.Record({
  'result' : IDL.Text,
  'title' : IDL.Text,
  'hypothesis' : IDL.Text,
  'experiment' : IDL.Text,
  'goals' : IDL.Text,
  'analysis' : IDL.Text,
});
export const LICPlan = IDL.Record({
  'id' : IDL.Text,
  'additionalInfo' : IDL.Text,
  'premiumDetails' : IDL.Text,
  'maturityDetails' : IDL.Text,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'benefits' : IDL.Text,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ProductInterest = IDL.Variant({
  'other' : IDL.Null,
  'unloadModifications' : IDL.Null,
  'moduleSelector' : IDL.Null,
  'licPlan' : IDL.Null,
  'groundworks' : IDL.Null,
  'tailorMadeModules' : IDL.Null,
});
export const Enquiry = IDL.Record({
  'submitter' : IDL.Principal,
  'city' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : Time,
  'productInterest' : IDL.Opt(ProductInterest),
  'phone' : IDL.Opt(IDL.Text),
});
export const PlanEntry = IDL.Record({
  'id' : IDL.Text,
  'content' : StructuredPlan,
  'metadata' : PlanMetadata,
  'poster' : ExternalBlob,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createOrUpdatePlan' : IDL.Func(
      [IDL.Text, PlanMetadata, ExternalBlob, StructuredPlan],
      [],
      [],
    ),
  'getAllLICPlans' : IDL.Func([], [IDL.Vec(LICPlan)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getEnquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Enquiry)], ['query']),
  'getLICPlanById' : IDL.Func([IDL.Text], [IDL.Opt(LICPlan)], ['query']),
  'getPlanById' : IDL.Func([IDL.Text], [IDL.Opt(PlanEntry)], ['query']),
  'getPlans' : IDL.Func([IDL.Nat], [IDL.Vec(PlanEntry)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'submitEnquiry' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Opt(ProductInterest),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updatePlan' : IDL.Func(
      [IDL.Text, PlanMetadata, ExternalBlob, StructuredPlan],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const PlanMetadata = IDL.Record({
    'title' : IDL.Text,
    'creator' : IDL.Principal,
    'createdAt' : Time,
    'description' : IDL.Text,
    'updatedAt' : Time,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const StructuredPlan = IDL.Record({
    'result' : IDL.Text,
    'title' : IDL.Text,
    'hypothesis' : IDL.Text,
    'experiment' : IDL.Text,
    'goals' : IDL.Text,
    'analysis' : IDL.Text,
  });
  const LICPlan = IDL.Record({
    'id' : IDL.Text,
    'additionalInfo' : IDL.Text,
    'premiumDetails' : IDL.Text,
    'maturityDetails' : IDL.Text,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'benefits' : IDL.Text,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ProductInterest = IDL.Variant({
    'other' : IDL.Null,
    'unloadModifications' : IDL.Null,
    'moduleSelector' : IDL.Null,
    'licPlan' : IDL.Null,
    'groundworks' : IDL.Null,
    'tailorMadeModules' : IDL.Null,
  });
  const Enquiry = IDL.Record({
    'submitter' : IDL.Principal,
    'city' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : Time,
    'productInterest' : IDL.Opt(ProductInterest),
    'phone' : IDL.Opt(IDL.Text),
  });
  const PlanEntry = IDL.Record({
    'id' : IDL.Text,
    'content' : StructuredPlan,
    'metadata' : PlanMetadata,
    'poster' : ExternalBlob,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createOrUpdatePlan' : IDL.Func(
        [IDL.Text, PlanMetadata, ExternalBlob, StructuredPlan],
        [],
        [],
      ),
    'getAllLICPlans' : IDL.Func([], [IDL.Vec(LICPlan)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getEnquiries' : IDL.Func([IDL.Nat], [IDL.Vec(Enquiry)], ['query']),
    'getLICPlanById' : IDL.Func([IDL.Text], [IDL.Opt(LICPlan)], ['query']),
    'getPlanById' : IDL.Func([IDL.Text], [IDL.Opt(PlanEntry)], ['query']),
    'getPlans' : IDL.Func([IDL.Nat], [IDL.Vec(PlanEntry)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'submitEnquiry' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Opt(ProductInterest),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updatePlan' : IDL.Func(
        [IDL.Text, PlanMetadata, ExternalBlob, StructuredPlan],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };